"""add provider metrics from rce

Revision ID: 016ac4edf3af
Revises: 70c809c27c09
Create Date: 2026-03-15 07:49:51.458536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '016ac4edf3af'
down_revision: Union[str, Sequence[str], None] = '70c809c27c09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


telemetry_chart_type_enum = sa.Enum(
    'line',
    'bar',
    name='telemetry_chart_type_enum',
)
telemetry_aggregation_mode_enum = sa.Enum(
    'raw',
    'hourly_integral',
    name='telemetry_aggregation_mode_enum',
)
provider_telemetry_capability_enum = sa.Enum(
    'power_meter',
    'energy_storage',
    'thermal',
    name='provider_telemetry_capability_enum',
)
scheduler_control_mode_enum = sa.Enum(
    'DIRECT',
    'POLICY',
    name='scheduler_control_mode_enum',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    telemetry_chart_type_enum.create(bind, checkfirst=True)
    telemetry_aggregation_mode_enum.create(bind, checkfirst=True)
    provider_telemetry_capability_enum.create(bind, checkfirst=True)
    scheduler_control_mode_enum.create(bind, checkfirst=True)
    op.create_table('market_energy_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('interval_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('price_unit', sa.String(length=16), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'interval_start', name='uq_market_energy_prices_market_interval_start')
    )
    op.create_index(op.f('ix_market_energy_prices_business_date'), 'market_energy_prices', ['business_date'], unique=False)
    op.create_index(op.f('ix_market_energy_prices_interval_end'), 'market_energy_prices', ['interval_end'], unique=False)
    op.create_index(op.f('ix_market_energy_prices_interval_start'), 'market_energy_prices', ['interval_start'], unique=False)
    op.create_index(op.f('ix_market_energy_prices_market'), 'market_energy_prices', ['market'], unique=False)
    op.add_column('devices', sa.Column('device_dependency_rule_json', sa.JSON(), nullable=True, comment='Structured source->target dependency rule for device runtime'))
    op.alter_column('provider_metric_definitions', 'chart_type',
               existing_type=sa.VARCHAR(length=32),
               type_=telemetry_chart_type_enum,
               existing_nullable=False,
               postgresql_using='chart_type::telemetry_chart_type_enum')
    op.alter_column('provider_metric_definitions', 'aggregation_mode',
               existing_type=sa.VARCHAR(length=32),
               type_=telemetry_aggregation_mode_enum,
               existing_nullable=False,
               postgresql_using='aggregation_mode::telemetry_aggregation_mode_enum')
    op.alter_column('provider_metric_definitions', 'capability_tag',
               existing_type=sa.VARCHAR(length=32),
               type_=provider_telemetry_capability_enum,
               existing_nullable=True,
               postgresql_using='capability_tag::provider_telemetry_capability_enum')
    op.drop_index(op.f('ix_provider_metric_samples_provider_metric_measured_at'), table_name='provider_metric_samples')
    op.add_column('scheduler_commands', sa.Column('command_payload_json', sa.JSON(), nullable=True))
    op.alter_column('scheduler_commands', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_scheduler_command_id'), 'scheduler_commands', type_='unique')
    op.drop_index(op.f('ix_scheduler_commands_command_id'), table_name='scheduler_commands')
    op.create_index(op.f('ix_scheduler_commands_command_id'), 'scheduler_commands', ['command_id'], unique=True)
    op.add_column('scheduler_slots', sa.Column('control_mode', sa.Enum('DIRECT', 'POLICY', name='scheduler_control_mode_enum'), server_default='DIRECT', nullable=False))
    op.add_column('scheduler_slots', sa.Column('control_policy_json', sa.JSON(), nullable=True, comment='Structured control policy dispatched to the agent for this slot'))
    op.add_column('scheduler_slots', sa.Column('device_dependency_rule_json', sa.JSON(), nullable=True, comment='Structured source->target dependency rule applied while slot is active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduler_slots', 'device_dependency_rule_json')
    op.drop_column('scheduler_slots', 'control_policy_json')
    op.drop_column('scheduler_slots', 'control_mode')
    op.drop_index(op.f('ix_scheduler_commands_command_id'), table_name='scheduler_commands')
    op.create_index(op.f('ix_scheduler_commands_command_id'), 'scheduler_commands', ['command_id'], unique=False)
    op.create_unique_constraint(op.f('uq_scheduler_command_id'), 'scheduler_commands', ['command_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('scheduler_commands', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('scheduler_commands', 'command_payload_json')
    op.create_index(op.f('ix_provider_metric_samples_provider_metric_measured_at'), 'provider_metric_samples', ['provider_id', 'metric_key', 'measured_at'], unique=False)
    op.alter_column('provider_metric_definitions', 'capability_tag',
               existing_type=provider_telemetry_capability_enum,
               type_=sa.VARCHAR(length=32),
               existing_nullable=True,
               postgresql_using='capability_tag::varchar')
    op.alter_column('provider_metric_definitions', 'aggregation_mode',
               existing_type=telemetry_aggregation_mode_enum,
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               postgresql_using='aggregation_mode::varchar')
    op.alter_column('provider_metric_definitions', 'chart_type',
               existing_type=telemetry_chart_type_enum,
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               postgresql_using='chart_type::varchar')
    op.drop_column('devices', 'device_dependency_rule_json')
    op.drop_index(op.f('ix_market_energy_prices_market'), table_name='market_energy_prices')
    op.drop_index(op.f('ix_market_energy_prices_interval_start'), table_name='market_energy_prices')
    op.drop_index(op.f('ix_market_energy_prices_interval_end'), table_name='market_energy_prices')
    op.drop_index(op.f('ix_market_energy_prices_business_date'), table_name='market_energy_prices')
    op.drop_table('market_energy_prices')
    bind = op.get_bind()
    scheduler_control_mode_enum.drop(bind, checkfirst=True)
    provider_telemetry_capability_enum.drop(bind, checkfirst=True)
    telemetry_aggregation_mode_enum.drop(bind, checkfirst=True)
    telemetry_chart_type_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
