"""add extra_data to provider_measurements

Revision ID: 2849c6fe9d33
Revises: a9a6cf87c41d
Create Date: 2026-03-01 15:22:30.224681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2849c6fe9d33'
down_revision: Union[str, Sequence[str], None] = 'a9a6cf87c41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider_measurements",
        sa.Column("extra_data", sa.JSON(), nullable=True),
    )
    op.execute(
        "UPDATE provider_measurements "
        "SET extra_data = '{}'::json "
        "WHERE extra_data IS NULL"
    )
    op.alter_column(
        "provider_measurements",
        "extra_data",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider_measurements", "extra_data")
    # ### end Alembic commands ###
