"""added power source providers

Revision ID: a9a6cf87c41d
Revises: a1f7b5c92d4e
Create Date: 2026-03-01 14:36:27.229338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9a6cf87c41d'
down_revision: Union[str, Sequence[str], None] = 'a1f7b5c92d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('providers', sa.Column('power_source', sa.String(length=32), nullable=True, comment='Selects which provider metric is treated as the primary power value'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('providers', 'power_source')
    # ### end Alembic commands ###
