"""add provider column

Revision ID: a5b3a38eaaea
Revises: a1f7b5c92d4e
Create Date: 2026-03-01 14:11:35.645602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b3a38eaaea'
down_revision: Union[str, Sequence[str], None] = 'a1f7b5c92d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scheduler_commands', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_scheduler_command_id'), 'scheduler_commands', type_='unique')
    op.drop_index(op.f('ix_scheduler_commands_command_id'), table_name='scheduler_commands')
    op.create_index(op.f('ix_scheduler_commands_command_id'), 'scheduler_commands', ['command_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduler_commands_command_id'), table_name='scheduler_commands')
    op.create_index(op.f('ix_scheduler_commands_command_id'), 'scheduler_commands', ['command_id'], unique=False)
    op.create_unique_constraint(op.f('uq_scheduler_command_id'), 'scheduler_commands', ['command_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('scheduler_commands', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###

