"""add extra_data to provider_measurements

Revision ID: 38efb6371b9c
Revises: 8df4becee0a4
Create Date: 2026-03-01 15:19:09.004532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38efb6371b9c'
down_revision: Union[str, Sequence[str], None] = '8df4becee0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider_measurements",
        sa.Column("extra_data", sa.JSON(), nullable=True),
    )
    op.execute(
        "UPDATE provider_measurements "
        "SET extra_data = '{}'::json "
        "WHERE extra_data IS NULL"
    )
    op.alter_column(
        "provider_measurements",
        "extra_data",
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider_measurements', 'extra_data')
    # ### end Alembic commands ###
