"""power_source enum to string

Revision ID: 8df4becee0a4
Revises: b45e57473962
Create Date: 2026-03-01 15:04:22.709661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8df4becee0a4'
down_revision: Union[str, Sequence[str], None] = 'b45e57473962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('providers', 'power_source',
               existing_type=postgresql.ENUM('INVERTER', 'METER', name='provider_power_source_enum'),
               type_=sa.String(length=32),
               existing_comment='Selects which provider metric is treated as the primary power value',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('providers', 'power_source',
               existing_type=sa.String(length=32),
               type_=postgresql.ENUM('INVERTER', 'METER', name='provider_power_source_enum'),
               existing_comment='Selects which provider metric is treated as the primary power value',
               existing_nullable=True)
    # ### end Alembic commands ###

